#!/usr/bin/env bash
# Configuring my nginx server to have a custom 404 page

apt-get update
apt-get -y install nginx

# Adding an HTML page

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

CONFIG=\
"server {
	listen 80 default_server;
  	listen [::]:80 default_server;

        root /var/www/html;

        index.html index.nginx-debian.html;

	error_page 404 /custom_404.html;

	server_name _;

	rewrite ^/redirect_me(.*)$ http://www.google.com/ permanent;

	location = /custom_404.html {
		root /usr/share/nginx/html;
		internal;
	}

        location / {
                try_files \$uri \$uri/ =404;
	}
}"

echo -e "$CONFIG" > /etc/nginx/sites-enabled/default

# Checking if service is running

state=$(pgrep nginx)

if [ -n "$state" ];
then
	sudo service nginx restart
	echo "Resarting Nginx, please wait"
else
	sudo service nginx start
	echo "Nginx has started"
fi
